### ISSUE TITLE
nuspec version says 0.5.1, but everything else points to 0.5.0

### ISSUE THREAD

**Issue by unindented** [euantorano/zig-chocolatey-package#2]
nuspec version says 0.5.1:

https://github.com/euantorano/zig-chocolatey-package/blob/21c1a5825fb4e849030ee4b2662d8c6a16db680b/zig.nuspec#L6

But then all other URLs, like the install URL, point to 0.5.0:

https://github.com/euantorano/zig-chocolatey-package/blob/21c1a5825fb4e849030ee4b2662d8c6a16db680b/tools/chocolateyInstall.ps1#L4

**Comment by euantorano** [comment]
Hi,

This is purposeful - the base NuGet package 0.5.0 was missing a dependency on VC Redist 2019. That was added, and the NuGet package was bumped to 0.5.1 to force an update.

The Zig version is still 0.5.0.

**Comment by unindented** [comment]
Ah, thanks for the clarification. Sorry about that!
